### ISSUE TITLE
Unexpected behaviour for numerical fields above 100 

### ISSUE THREAD

**Issue by mkffl** [ThaminduR/spark-privacy-preserver#13]
Thanks for consolidating all these great privacy methods into one package. This may not be an issue but rather a misunderstanding about the intention behind non categorical fields. 

It seems that `agg_numerical_column`, which groups partitions with numerical fields, creates labels based on the last two digits of the min and max of a series. That, in turn, creates surprising results for fields with a range above 100, e.g. zip codes.

Concretely, a partition with range 120-190 gets the same label as one with range 220-290. Is that the intended behaviour?

**Comment by ThaminduR** [comment]
Intended behavior was to group numerical values gracefully rather than taking the min and the max values of a partition. It seems like there is a logical error in the ``agg_numerical_column``` .

**Comment by mkffl** [comment]
Do you have any external reference that explains/shows what how this method should work, ideally with code that does not include any logical error? 

It's a shame that `agg_numerical_column` does not work exactly as it should but I am happy to have a try at fixing it and submitting a PR. I just a need a pointer.

**Comment by agessner** [comment]
Any update on this?

**Comment by ThaminduR** [comment]
What the `agg_numerical_column` is intended to do is, take the min and max of the column and then round them up to the nearest x5 multiplier. 

Intended behavior:
- A column with values ranging from 3 to 9 would be aggregated to `0-10`
- A column with values ranging from 236 to12343 would be aggregated to `235-12345`

If you have any suggestions to do this in another way, feel free to add those here.

**Comment by ThaminduR** [comment]
I fixed the function to do the intended task. Check the [PR](https://github.com/ThaminduR/spark-privacy-preserver/pull/14).
@mkffl @agessner 

Test the function and add a comment here. If we are good to go, I'll merge the pr.
